# Generated by Django 5.1.2 on 2024-12-16 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_remove_doctorappointment_doctor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorappointment',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='doctor_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='Doctor.doctorprofile'),
            preserve_default=False,
        ),
    ]
