# Generated by Django 5.1.2 on 2024-12-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_remove_doctorappointment_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='doctor_name',
            field=models.CharField(max_length=255),
        ),
    ]
