# Generated by Django 5.1.2 on 2025-01-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0006_remove_doctorappointment_doctor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
