# Generated by Django 5.1.2 on 2024-11-01 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('username', models.CharField(default='default_username', max_length=50, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='doctor_pics/')),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages_spoken', models.CharField(blank=True, max_length=200, null=True)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('special_notes', models.TextField(blank=True, null=True)),
                ('doctor_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='Doctor.doctorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('medical_license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('license_issuing_authority', models.CharField(blank=True, max_length=100, null=True)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('doctor_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_info', to='Doctor.doctorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SystemFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('doctor_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_fields', to='Doctor.doctorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_hospital', models.CharField(blank=True, max_length=200, null=True)),
                ('office_address', models.TextField(blank=True, null=True)),
                ('consultation_hours', models.CharField(blank=True, max_length=50, null=True)),
                ('working_days', models.CharField(blank=True, max_length=100, null=True)),
                ('teleconsultation', models.BooleanField(default=False)),
                ('doctor_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_details', to='Doctor.doctorprofile')),
            ],
        ),
    ]
