# Generated by Django 5.1.2 on 2025-02-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0008_doctorprofile_experience_doctorprofile_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinformation',
            name='clinic_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
